[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
swap = "B7TKWwRjzkTKb9kc5VSA9gawufx6SmbkViyx2GmMFtWL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./swap.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
