[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
swap = "7AXBs6wHosutsXd11Q3zdNJ4LS9p9XE3bX3nJfvfGunU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./chaidex.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
