[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
swap = "EPwQBZMG7y7VbijnPfPk7qgqR78TvZucSFP14zygkrAS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./swap.json"


[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
