[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
swap = "8Mi1JhPQHTHHaLFhLUMLZGRbVMc9D4sZtUubSRpxhpNP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./swap.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
