const anchor = require('@coral-xyz/anchor');
const fs = require('fs');
const { PublicKey, SystemProgram, Keypair, Connection, clusterApiUrl } = anchor.web3;
const BN = anchor.BN;  // Make sure BN is imported

// Main async function to run the backend
async function main() {
    // 1. Set up a connection to the Solana cluster (here, devnet)
    const connection = new Connection(clusterApiUrl('devnet'));

    // User A (swap.json) and User B (chaidex.json) keypairs
    const userA = Keypair.fromSecretKey(new Uint8Array(require("../swap.json")));
    const userB = Keypair.fromSecretKey(new Uint8Array(require("../chaidex.json")));

    // Replace with actual CT Token Mint address
    const tokenMintA = new PublicKey("J1q7FEiMhzgd1T9bGtdh8ZTZa8mhsyszaW4AqQPvYxWX");
    const tokenMintB = new PublicKey("J1q7FEiMhzgd1T9bGtdh8ZTZa8mhsyszaW4AqQPvYxWX");

    // 2. Use userA as the wallet for this transaction
    const wallet = new anchor.Wallet(userA);

    // 3. Create an Anchor provider using the connection and wallet
    const provider = new anchor.AnchorProvider(connection, wallet, {
        preflightCommitment: 'processed',
    });
    anchor.setProvider(provider);
    console.log("Provider set up successfully.");

    // 4. Load the program IDL (generated by Anchor)
    const idl = JSON.parse(fs.readFileSync('../target/idl/swap.json', 'utf8'));

    console.log("IDL loaded successfully.");


    // 5. Specify your deployed program’s ID (as declared in your Rust code)
    const programId = new PublicKey("EPwQBZMG7y7VbijnPfPk7qgqR78TvZucSFP14zygkrAS");
    console.log("Program ID:", programId.toBase58());
    let program;
    try {
        program = new anchor.Program(idl, programId, provider);
        console.log("Program loaded successfully.");
    } catch (err) {
        console.error("Failed to initialize program:", err);
        console.log("IDL accounts:", JSON.stringify(idl.accounts, null, 2));
        console.log("IDL types:", JSON.stringify(idl.types.filter(t => idl.accounts.some(a => a.name === t.name)), null, 2));
        return;
    }
    // 7. Subscribe to program events
    program.addEventListener("CreateTradeEvent", (event, slot) => {
        console.log("CreateTradeEvent received:", event);
        console.log("Slot:", slot);
    });

    program.addEventListener("InterchainSwapCompletedEvent", (event, slot) => {
        console.log("InterchainSwapCompletedEvent received:", event);
        console.log("Slot:", slot);
    });

    // 8. Derive PDAs (program-derived addresses) required by your instructions.
    // Here we use an example trade id (as a BN) and convert it to an 8-byte little-endian buffer.
    const tradeId = new BN(1);
    const tradeIdBuffer = tradeId.toArrayLike(Buffer, "le", 8);

    // Derive the Offer PDA (seeds: [b"offer", maker, id])
    const [offerPda, offerBump] = PublicKey.findProgramAddressSync(
        [Buffer.from("offer"), wallet.publicKey.toBuffer(), tradeIdBuffer],
        program.programId
    );
    console.log("Offer PDA:", offerPda.toBase58(), "Bump:", offerBump);

    // Derive the Vault PDA (for native SOL deposits: seeds: [b"vault-native", maker, id])
    const [vaultPda, vaultBump] = PublicKey.findProgramAddressSync(
        [Buffer.from("vault-native"), wallet.publicKey.toBuffer(), tradeIdBuffer],
        program.programId
    );
    console.log("Vault PDA:", vaultPda.toBase58(), "Bump:", vaultBump);

    // 9. Call an instruction on your program.
    // Here we demonstrate calling the deposit_seller_native instruction.
    // Note: Use the account names as defined in the IDL.
    try {
        const tx = await program.methods
            .depositSellerNative(
                tradeId,                                   // id (u64)
                new BN(15000000000),                       // token_b_wanted_amount (15 CT in smallest units)
                new BN(100000000),                         // sol_offered_amount (lamports)
                false,                                     // is_taker_native
                new BN(Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 7)  // deadline (current time + 7 days)
            )
            .accounts({
                maker: userA.publicKey,
                tokenMintA: tokenMintA,
                tokenMintB: tokenMintB,
                offer: offerPda,
                vault: vaultPda,
                systemProgram: SystemProgram.programId,
                clock: anchor.web3.SYSVAR_CLOCK_PUBKEY,
            })
            .signers([userA])
            .rpc();

        console.log("✅ Transaction successful! Signature:", tx);
    } catch (err) {
        console.error("Transaction failed:", err);
    }

    // 10. Keep the process alive so that the event listeners remain active.
    console.log("Listening for events... (press CTRL+C to exit)");
    process.stdin.resume();
}

// Run main and catch any errors
main().catch(err => {
    console.error(err);
});
